### PR TITLE
buffer large object connection

### PR DESCRIPTION
**Pull request by Virv12**

### CODE REVIEW

**Comment by veluca93** [comment]
What's the effect of this change?

**Comment by Virv12** [comment]
When accessing largeobject over a network cms is not capable of streaming correctly the content but waits for the server ack for every chunk sent, effectively spending one RTT every chunk. Adding a 64MB buffer mitigates this effect.

**Comment by veluca93** [comment]
> When accessing largeobject over a network cms is not capable of streaming correctly the content but waits for the server ack for every chunk sent, effectively spending one RTT every chunk. Adding a 64MB buffer mitigates this effect.

can you write that in the commit description?

**Comment by Virv12** [comment]
Done

**Pull request merged**
